[book]
title = "Rust Embedded Drivers Book"
authors = []
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/ImplFerris/red-book"
cname = "mb2.implrust.com"
preferred-dark-theme = "ayu"
default-theme = "light"
mathjax-support = true

# Don't show table of contents for entire page in the navigation bar
# Pretty confusing to look at the chapter 
sidebar-header-nav = false

# [output.html.playground]
# editable = true

[output.html.fold]
enable = true
level = 1     # the depth to start folding
